package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "part1",
    srcs = ["part1.cpp"],
    data = ["input.txt"],
)

cc_binary(
    name = "part2",
    srcs = ["part2.cpp"],
    data = ["input.txt"],
)
